---
- name: "Add new group {{ item.group }}"
  ansible.builtin.group:
    name: "{{ item.group | default(item.name) }}"
    state: "{{ item.state | default('present') }}"
  when: item.name != 'root'

- name: "Add new user {{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(item.name) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(item.name) }}"
    groups: "{{ item.groups | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    shell: '/bin/bash'
    createhome: "{{ item.createhome | default(true) }}"
    state: "{{ item.state | default('present') }}"
  when: item.name != 'root'

- name: "Deploy public keys for {{ item.name }}"
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.sshpubkey }}"
    exclusive: "{{ item.exclusive | default('true') }}"
    state: "{{ item.state | default('present') }}"
  when: item.name != 'root' and item.sshpubkey is defined
